version: "3.8"

services:
    db:
        image: postgres
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/com-word-app2
        ports:
        - "8000:8000"
        depends_on:
        - db
    front:
        build:
            context: ./frontend
        command: "npm run serve"
        stdin_open: true
        volumes:
            - .:/com-word-app2
        ports:
            - "8080:8080"